
name: Build

on:
  push:
    branches: [ develop ] # never pushing directly to main so no push check on main
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/voismart/freeswitch-sdk:ci
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ${{ runner.os }}-ccache-${{ github.ref }}-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Configure & Build
        run: |
          set -eux
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ \
                -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build -j"$(nproc)"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/**/*.so
            build/**/*.a
            build/**/*.dll
            build/**/*.dylib
            build/**/*.exe
            build/compile_commands.json
          if-no-files-found: ignore
