
name: CD

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO: ${{ github.repository }}

jobs:
  release_github:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.ref_name }} \
            -R $REPO \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes
